server:
  port: 8888


mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.annie.persistent.entity
  config-location: classpath:mybatis/mybatis-config.xml


spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/static/
    content-type: text/html
    mode: HTML5
#  profiles: dev
  datasource:
    url: jdbc:mysql://39.108.129.219:3306/annie_shop_test?useUnicode=true&characterEncoding=utf-8
    username: blade
    password: 7m0#!76&BS@Y8Nbp
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
# spring 对静态资源管理
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
logging:
  config: classpath:log4j2.xml
