server:
  port: 8888


mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.annie.persistent.entity
  config-location: classpath:mybatis/mybatis-config.xml


spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/static/
    content-type: text/html
    mode: HTML5
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/annie_shop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver